# This is a docker-compose file for a Next.js application with MongoDB
networks:
  gen-image-net:
    driver: bridge

services:
  # FrontEnd as Vite.js application
  gen-image-app:
    hostname: gen-image
    depends_on:
      - gen-image-server
    container_name: gen-image
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    restart: always
    ports:
      - "5173:4173"
    # BackEnd as Express.js application
  gen-image-server:
    hostname: gen-image-server
    container_name: gen-image-server
    env_file:
      - ./server/.env
    depends_on:
      - gen-image-db
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    restart: always
    ports:
      - "5174:8080"
  gen-image-db:
    hostname: gen-image-mongo-db
    container_name: gen-image-mongo-db
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: example
      # Create a new database. Please note, the
      # /docker-entrypoint-initdb.d/init.js has to be executed
      # in order for the database to be created
      MONGO_INITDB_DATABASE: users
    volumes:
      # Add the db-init.js file to the Mongo DB container
      - ./db-init.js:/docker-entrypoint-initdb.d/init.js:ro
    ports:
      - "5175:27017"
# docker-compose build --no-cache
# docker-compose up -d --build
